export const CART_ACTIONS = {
    ADD_TO_CART: "ADD_TO_CART",
    MANAGE_QUANTITY: "MANAGE_QUANTITY",
    REMOVE_FROM_CART: 'REMOVE_FROM_CART'
}

export const CATEGORY_ACTIONS = {
    CATEGORY_LIST_LOADING: 'CATEGORY_LIST_LOADING',
    CATEGORY_LIST_SUCCESS: 'CATEGORY_LIST_SUCCESS',
    CATEGORY_LIST_FAILED: "CATEGORY_LIST_FAILED"
}